[General]
; --- Window Settings ---
WindowWidth = 1300
WindowHeight = 850
FontName = Hack
FontSize = 9

; --- Automation Settings ---
ScanIPs = 89.223.66.97
TargetAppPrefixes = FoldingAtRunOnFlux,socks555,KaspaNode
AutomationIntervalSeconds = 300

; --- Logging Settings ---
Debug = false
LogFile = session.log
LogClearOnStart = true
MaxLogHistory = 1000

